spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop        # use 'create-drop' for dev
    show-sql: true
  profiles:
    active: dev

server:
  port: ${PORT:8080}